name: test_action

on:
  push:
    branches: [ action ]
  pull_request:
    branches: [ main ]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: arthurpalves/coherent-swift@main
      with:
        sources: Sources/
        minimum_threshold: 60
        ignore_output_result: true
        only_changes: false
        report_format: plain
